### PR TITLE
drop source build of fake_joint_driver

### PR DESCRIPTION
**Pull request by jschleicher**
since it is now available as melodic package

### CODE REVIEW

**Comment by DamKoVosh** [comment]
Is it possible, that fake_joint is not yet accessable in apt? Can't install it however

**Comment by jschleicher** [comment]
Obviously it's still in [Testing](http://wiki.ros.org/action/fullsearch/TestingRepository). 
See http://repositories.ros.org/status_page/melodic_default.html?q=fake-joint

Thus Travis succeeds but you'd have to wait for the next [sync](https://discourse.ros.org/c/release/melodic/38) probably in the next few days if you don't want to change your sources.list

So we'd defer this PR until after the next sync?

**Comment by DamKoVosh** [comment]
Yes lets do that

**Comment by DamKoVosh** [comment]
https://discourse.ros.org/t/preparing-for-melodic-sync-2020-01-10/12255?u=richard_feistenauer
sync is out

**Review by DamKoVosh — APPROVED** [review]

**Pull request merged**
